### ISSUE TITLE
incorrect column width with Chinese characters

### ISSUE THREAD

**Issue by huashan** [Rapporter/pander#144]
Hi, I recently encounter this problem after several updates of pander (now is 0.5.2). I couldn't figure it out. Below is the demo code, see the extra white space around the Chinese string and column width is broken.

```r
> aa = data.frame(v1 = c('一个很长的中文中文中文中文中文中文中文中文字符串', 'b', 'c'), v2 = 1:3)
> pandoc.table(aa, split.tables=Inf, split.cells=Inf)

-----------------------------------------------------
                       v1                         v2 
------------------------------------------------ ----
            一个很长的中文中文中文中文中文中文中文中文字符串            1  

                       b                          2  

                       c                          3  
-----------------------------------------------------
```

**Comment by daroczig** [comment]
@RomanTsegelskyi, did you have some time to check this issue in more details? If not, no problem, just let me know. Thanks!

**Comment by RomanTsegelskyi** [comment]
I am sorry, I didn't have much time to look into it. I hope to have more time upcoming days.

**Comment by RomanTsegelskyi** [comment]
@daroczig. I have explored more and I am not sure how the issue can be fixed. 
First of all, v0.3.8 does not seem to work for the examples given.
```
> pandoc.table(aa, split.tables=Inf, split.cells=Inf)

-----------------------------------------------------
                       v1                         v2 
------------------------------------------------ ----
一个很长的中文中文中文中文中文中文中文中文字符串  1  

                       b                          2  

                       c                          3  
-----------------------------------------------------

> 
> pander(data.frame(x=1, abcd=c('乂乂乂')), style = "grid")


+-----+--------+
|  x  |  abcd  |
+=====+========+
|  1  | 乂乂乂 |
+-----+--------+
```
In general the problem, IMHO is how to determine printing width for string with CJK characters.
For example, for string '一个很长的中文中文中文中文中文中文中文中文字符串' `nchar(..., type='width)` returns printing width of 48. But it's this string does not have the same printing width as the string with 48 characters. 

```
> '一个很长的中文中文中文中文中文中文中文中文字符串'
[1] "一个很长的中文中文中文中文中文中文中文中文字符串"
> '                       c                        '
[1] "                       c                        "
> nchar( '一个很长的中文中文中文中文中文中文中文中文字符串', 'width')
[1] 48
> nchar('                       c                        ', 'width')
[1] 48
```
And whole table rendering is based on first determing the max printing width and then using it for other columns. But in the example above, priting width that we get from `nchar` is not correct, so whole rendering goes wrong.
I tried using `R` `format` instead of `format_cpp`, but that does not help, because `format` is also based on `nchar`.
What do you think?

**Comment by daroczig** [comment]
Not sure. These look fine in my console, although when I copy to the GH comment, the widths are not OK. Probably I'm using some auto-magical fonts on my localhost :)

Quick demo:
![nchar48](https://cloud.githubusercontent.com/assets/495736/5790488/c0ba54a6-9e9b-11e4-8c05-914789dbdb67.png)

The `abcd` demo:
![example1](https://cloud.githubusercontent.com/assets/495736/5790490/ea6e90fa-9e9b-11e4-9534-6f9acdc9a2cd.png)

The `aa` demo:
![example2](https://cloud.githubusercontent.com/assets/495736/5790495/1888a0a2-9e9c-11e4-97cd-9f4b8c61f872.png)

But when I copy to the here:

```r
-----------------------------------------------------
                       v1                         v2 
------------------------------------------------ ----
一个很长的中文中文中文中文中文中文中文中文字符串  1  
-----------------------------------------------------
```

Which looks ugly here, but `pandoc` handles it nicely:

<table>
<colgroup>
<col width="68%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">v1</th>
<th align="center">v2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">一个很长的中文中文中文中文中文中文中文中文字符串</td>
<td align="center">1</td>
</tr>
</tbody>
</table>

PS: the above examples were generated by falling back to the slow and ugly `R` solution in `table.expand` when `(all(nchar(cells) == nchar(cells, type = 'byte')))` is `FALSE`.

So the question is now if you can replicate the above results in the R console or it's only working here.

**Comment by RomanTsegelskyi** [comment]
I somehow missed the idea that it can be connected to a font. On Mac console everything works fine. Weird examples that I got were from RStudio console. I made a fix (#148) in C++ part, so now it looks like it gives same results as v0.3.8. What should we do with different fonts?

**Comment by daroczig** [comment]
Thank you @RomanTsegelskyi, IMHO this is enough (I mean: great), as we cannot handle client-side issues (font) within the R package.

@huashan: can you please report back if it's working fine?

**Comment by huashan** [comment]
Yes, I confirm it's working well with Chinese characters. Thank you @RomanTsegelskyi and @daroczig
