### ISSUE TITLE
Formatting by Column/Row

### ISSUE THREAD

**Issue by mattsigal** [Rapporter/pander#146]
I recently switched from xtable to pander, and am really impressed with this package.  Thanks so much for your work!

In the transition, I've come across two issues which I'm hoping to get your input on:

1) In xtable, I could supply a numeric vector to digits to apply them to each column, respectively.  For example, I could supply digits = c(0,1,2,3) to have the first column have 0 decimal places, the second column 1, et cetera.  This was very useful because I have some columns with integers, and others that require rounding.  As far as I can tell, though, with pander I could only specify digits = X, and have it apply to the entire table.  Am I missing something?

2) Similarly, in xtable, I could use hline.after when calling print() to specify where I would like horizontal lines.  I know pander can produce horizontal lines, but cannot figure out how to add them manually?

Any advice would be appreciated!

**Comment by daroczig** [comment]
Thanks for the great ideas.

Unfortunately the 2nd one will not work, as the style and markup of the table structure is really strict, and there's not much option to add/remove lines it. Please see more details in the [Pandoc's markdown manual](http://johnmacfarlane.net/pandoc/README.html).

But the 1st suggestion should work, I'll be happy to start working on it -- although probably not in the next two weeks, as currently I'm moving to a new home.

**Comment by RomanTsegelskyi** [comment]
Fixed in #190
