### ISSUE TITLE
pander method for tabular object

### ISSUE THREAD

**Issue by MikeKSmith** [Rapporter/pander#147]
The tabular package has methods for producing HTML or LaTeX output tables, but not markdown. Pander can format basic (non-nested) tables from tabular if you convert first to matrix (this is kind of a cheat!). However the nested tables that tabular can generate present a problem.
e.g. tabular(as.factor(am) ~ (mpg+hp+qsec)*(mean+median), data=mtcars)

**Comment by daroczig** [comment]
Thank you for this report. Can you please elaborate a bit more on how to improve `pander` to handle `tables::tabular` objects?  Currently, your proposed `matrix` hack seems to work on your example as well:

```r
> pander(as.matrix(tabular(as.factor(am) ~ (mpg+hp+qsec)*(mean+median), data=mtcars)))

------------- ----- ------ ----- ------ ----- ------
               mpg          hp          qsec        

as.factor(am) mean  median mean  median mean  median

      0       17.15  17.3  160.3  175   18.18 17.82 

      1       24.39  22.8  126.8  109   17.36 17.02 
------------- ----- ------ ----- ------ ----- ------
```

Do you miss the highlighted col/row names, or you would like to simply avoid the `matrix` hack and let us `pander` do that extra step automatically? Unfortunately the limitations of markdown (like no row/col spanning is supported) suggests to keep the table structure/design at a minimal level.

**Comment by MikeKSmith** [comment]
Many thanks for your prompt response. 



I realise that there's a limitation with markdown for spanning tables - it's a shame, but an understandable "feature" given the possible levels of complexity. 


Would it be at all possible to define a numeric value for the number of rows / columns in the "header" to define where the numeric values in the table lie in order to get *some* formatting back? For example, below we have rowheader=2. 



               mpg           hp           qsec         

as.factor( am ) mean   median mean   median mean   median 

------------- ----- ------ ----- ------ ----- ------ 

      0        17.15   17.3   160.3   175    18.18 17.82 

      1        24.39   22.8   126.8   109    17.36 17.02 
------------- ----- ------ ----- ------ ----- ------ 



or with the "grid" format: 



+-------------+-----+------+-----+------+-----+------+ 
|    &nbsp;   | mpg  |      | hp   |      | qsec |      | 
|as.factor( am )| mean| median| mean | median| mean  | median| 

+=============+=====+======+=====+======+=====+======+ 
| ** 0**        | 17.15| 17.3  | 160.3| 175   | 18.18| 17.82 | 
+-------------+-----+------+-----+------+-----+------+ 
| ** 1**        | 24.39| 22.8  | 126.8| 109   | 17.36| 17.02 | 
+-------------+-----+------+-----+------+-----+------+ 


Best regards, 

Mike 



----- Original Message -----

**Comment by daroczig** [comment]
So you want the following two lines to behave as the table header?

```r
               mpg          hp          qsec        

as.factor(am) mean  median mean  median mean  median
```

And having the rest as the normal table body, so something like this:

```r
> m <- as.matrix(tabular(as.factor(am) ~ (mpg+hp+qsec)*(mean+median), data=mtcars))
> colnames(m) <- apply(m[1:2, ], 2, paste, collapse = '\\ \n')
> pander(m[-(1:2), ], keep.line.breaks = TRUE, split.table = Inf)

------------------------------------------------------------------
      \          mpg\      \      hp\      \      qsec\      \    
 as.factor(am)   mean    median   mean   median    mean    median 
--------------- ------- -------- ------ -------- -------- --------
       0         17.15    17.3   160.3    175     18.18    17.82  

       1         24.39    22.8   126.8    109     17.36    17.02  
------------------------------------------------------------------
```

Please note that the extra `\`chars are needed for `pandoc` as hard line-breaks.

**Comment by MikeKSmith** [comment]
Thanks. That looks about right...

**Comment by MikeKSmith** [comment]
Thanks - that looks good.

**Comment by daroczig** [comment]
If you can provide a few extra examples on `tables::tabular`, probably I can come up with a generalized solution, which could be automatically applied to all similar objects, without calling the above workaround.  Do you think it's possible? E.g. the number of "header rows" is always 2? Or it can be found somewhere in the object or guessed? It seems that some `attr` can be very helpful here, e.g.:

```r
> attr(tabular(as.factor(am) ~ (mpg+hp+qsec)*(mean+median), data=mtcars), 'colLabels')
     [,1]   [,2]     [,3]   [,4]     [,5]   [,6]    
[1,] "mpg"  NA       "hp"   NA       "qsec" NA      
[2,] "mean" "median" "mean" "median" "mean" "median"
```

But I would need a number of further examples with more complex tables to start working on `tables::tabular` support.

**Comment by daroczig** [comment]
I ended up using this thread as a test case for [GSoC 2015](https://github.com/rstats-gsoc/gsoc2015/wiki/pander).

**Comment by daroczig** [comment]
@MikeKSmith Please try the development version and provide some feedback how you like the new feature introduced as the first step of GSoC 2015 by @RomanTsegelskyi
