### ISSUE TITLE
An additional functionality enabling production of beautiful summary tables obtained from the randomForest package

### ISSUE THREAD

**Issue by konradedgar** [Rapporter/pander#153]
It would be beneficial if *pander* could support production of beautiful summary tables from the random forest model output. The code below would illustrate how the pander could be used

```R
# Set up
rm(list = ls())
data(airquality)
attach(airquality)
packs <- c("randomForest", "pander")
lapply(packs, require, character.only=T, quietly = TRUE, warn.conflicts = FALSE)

# Model
airquality <- na.roughfix(airquality)
dummy <- randomForest(Ozone ~., data = airquality)

# Desired usability
pander(dummy)
```

**Comment by daroczig** [comment]
Thanks, this is a really good suggestion. I won't be able to add this functionality to the package in the near future, but hopefully someone will work actively on the package via [GSoC 2015](https://github.com/rstats-gsoc/gsoc2015/wiki) this summer, so should be resolved in a few months. If not, then I'll take care of it, but first let's wait for some GSoC feedback.

**Comment by konradedgar** [comment]
Thanks for showing the interest in this modest problem.

**Comment by daroczig** [comment]
Ping @RomanTsegelskyi

**Comment by daroczig** [comment]
@konradedgar, @RomanTsegelskyi just added support for `randomForest` objects -- although not in tabular format. Please let us know some feedback on the result:

```r
> pander(dummy)

Call:  randomForest(formula = Ozone ~ ., data = airquality) 
Type of random forest: regression
Number of trees: 500
No. of variables tried at each split: 1

Mean of squared residuals: 334.007
% Var explained: 60.17
```

And if you can suggest a tabular version of this, then how it would look like. None of the `xtable`, `stargazer`, broom` packages provides examples on this.
