### ISSUE TITLE
Lists not rendering properly?

### ISSUE THREAD

**Issue by andrewcstewart** [Rapporter/pander#154]
I'm getting the following:

```
foo = list(a = "hi", b="bye")
library(pander)
pander(foo)
```

* a: [1] “hi” attr(,“class”) [1] “knit_asis” attr(,“knit_cacheable”) [1] TRUE
* b: [1] “bye” attr(,“class”) [1] “knit_asis” attr(,“knit_cacheable”) [1] TRUE

**Comment by daroczig** [comment]
Sorry for the long delay with my reply. Which version of `pander` are you using? It seems to work fine with the dev version here:

```r
> foo = list(a = "hi", b="bye")
> library(pander)
> pander(foo)


  * **a**: hi
  * **b**: bye

<!-- end of list -->
```

Although I've not tested the CRAN version for a long time.

**Comment by andrewcstewart** [comment]
Ah, I was using the CRAN version.  install via devtools works fine.  Thanks!

**Comment by daroczig** [comment]
Thanks for the feedback -- I will try to push a new version to CRAN later this month.
