### ISSUE TITLE
emphasize is not working for NA and empty string.

### ISSUE THREAD

**Issue by byzheng** [Rapporter/pander#156]
I am using the latest version in github.

My data.frame includes some missing values with NA. pandoc.table cannot generate the correct table when emphasize is used. I also find the same issue for empty string.

This is my minimum example to reproduce my problem.

	library(pander)
	df <- data.frame(x1 = c(1, 2, 3), x2 = c(1, NA, 3), 
					 x3 = c('A', '', 'C'), 
					 x4 = c('A', ' ', 'C'), 
					 x5 = c('A', ' B', 'C'))
	pandoc.table(df, emphasize.cols = 1)
	pandoc.table(df, emphasize.cols = 2)
	pandoc.table(df, emphasize.cols = 3)
	pandoc.table(df, emphasize.cols = 4)
	pandoc.table(df, emphasize.cols = 5)

Just show results for this command:

	pandoc.table(df, emphasize.cols = 4)

	------------------------
	 x1   x2   x3   x4   x5 
	---- ---- ---- ---- ----
	 1    1    A   *A*   A  

	 2    NA       *A*   B  

	 3    3    C   *A*   C  
	------------------------

	Warning message:
	In `[<-.data.frame`(`*tmp*`, , emphasize.cols, value = list("*A*",  :
	  provided 3 variables to replace 1 variables

I expect *A*, **, *C* in column X4.

	sessionInfo()

	R version 3.1.1 (2014-07-10)
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	locale:
	[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
	[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
	[5] LC_TIME=English_Australia.1252    

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     

	other attached packages:
	[1] pander_0.5.2

	loaded via a namespace (and not attached):
	[1] digest_0.6.4 Rcpp_0.11.3  tools_3.1.1

**Comment by daroczig** [comment]
Thanks for the bug report, it should be fixed with the recent commit. Pls let me know how it works for you.
