### ISSUE TITLE
Missing column and row title in CrossTable

### ISSUE THREAD

**Issue by Chris-M-P** [Rapporter/pander#163]
Thanks for an excellent package.

A minor niggle: column and row titles from `descr::CrossTable` appear to be missing. In this example:

    library(descr)
    CrossTable(mtcars$cyl, mtcars$gear, prop.c = FALSE, prop.t = FALSE, chisq = FALSE, prop.chisq = FALSE)

'mtcars$cyl' is the title for rows and 'mtcars$gears' for columns. When I run it through `pander`:

    library(descr)
    library(pander)
    pander(CrossTable(mtcars$cyl, mtcars$gear, prop.c = FALSE, prop.t = FALSE, chisq = FALSE, prop.chisq = FALSE))

The row and column titles are now lost.

**Comment by Chris-M-P** [comment]
I may be wrong on this, but it seems that Pandoc does not support column spanning cells, which would be necessary for a row with column titles - does this sound right? If so, I can't think of a good way in which a title row could be added.

**Comment by RomanTsegelskyi** [comment]
@Chris-M-P thanks for reporting this issue. I think it is possible to fix it, I made a change in #165. Please have a look at it in RomanTsegelskyi/pander, if it's good, I will merge it

**Comment by Chris-M-P** [comment]
That works fine, thanks.

**Comment by Chris-M-P** [comment]
Sorry, I may have spoken too soon. It works well in html and doc, but with long variable names and full width tables it doesn't work well for pdfs. Unfortunately, I don't have an example I can share to hand. It may be an issue with the latex rendering of the table, where latex is making decisions about column widths and overriding the necessity to fit the variable names in without overlapping. Html and word just seem to squash the tables in as needed!

**Comment by daroczig** [comment]
@Chris-M-P my ultimate workaround on too wide LaTeX tables is usually tweaking (lowering) the `split.table` and `split.cells` options, or using some nifty table environment instead of the default one.

**Comment by daroczig** [comment]
Closing this. Please reopen with some more details so that we can identify if it's a `pander` or markdown issue.
