### ISSUE TITLE
Named integer vectors not printing as expected

### ISSUE THREAD

**Issue by mhminai** [Rapporter/pander#166]
When I try to pander a named integer vector, I get just the integers, the names are removed.
MWE:
```
    a <- c(seq(1,10))
    names(a) <- letters[1:length(a)]
    print(a)
     a  b  c  d  e  f  g  h  i  j 
     1  2  3  4  5  6  7  8  9 10 
    pander(a)
    _1_, _2_, _3_, _4_, _5_, _6_, _7_, _8_, _9_ and _10_
```
I would have expected pander to retain at least the "names" attribute as it usually contains relevant information. In my case I have a vector of sums of the columns of a data frame.
```
a <- c(1,2,3)
b <- c(4,5,6)
df <- data.frame(a,b)
apply(df,2,sum)
a  b 
6 15 
pander(apply(df,2,sum))
_6_ and _15_
```

In this case, possibly a tabular format might be more suitable. I tried using the `as.table` function, but that also did not give me what I was expecting
```
as.table(apply(df,2,sum))
a  b 
6 15 
pander(as.table(apply(df,2,sum)))

- --
6 15
- --

```

Please note that #9 could be related.

**Comment by mhminai** [comment]
coercing to matrix seems to work.
```
pander(as.matrix(apply(df,2,sum)))

------- --
 **a**  6 

 **b**  15
------- --
```

**Comment by daroczig** [comment]
Thanks for the report. I think has been already resolved with the development version of `pander`:

```r
>     pander(a)

---------------------------------------
 a   b   c   d   e   f   g   h   i   j 
--- --- --- --- --- --- --- --- --- ---
 1   2   3   4   5   6   7   8   9  10 
---------------------------------------
```

I'm just about to release a new version on CRAN, but having [some issues](https://stat.ethz.ch/pipermail/r-devel/2015-April/070981.html) with `R CMD check` -- that hopefully I will be able to resolve soon. Until then, pls use the dev build, and re-open this ticket if you still face the same/similar issue.
