### ISSUE TITLE
pandoc.table empty cells

### ISSUE THREAD

**Issue by HJAllen** [Rapporter/pander#167]
pandoc.table is removing empty cells.  I am developing a document in RStudio using rmarkdown.  Part of the document is a signature page.  i have a function to create a data.frame from supplied names and titles.  I am trying to use empty cells to keep vertical spacing between each name for actual signatures.  When using pander to render table to a .docx, all of the empty cells have been removed.  Is there a way around this?
Thanks!

```
sig.func<-function(sigs=list(c('Name1','Title1'),c('Name2','Title2'))){
  sig.mat<-do.call('rbind',lapply(sigs,function(x){
    data.frame(first=c('_________________________________________________________',x[1],x[2],' ',' ', ' '),
               second=c('_______________','Date',' ',' ',' ',' '))
    }))
  colnames(sig.mat)<-c(' ',' ')
  sig.mat
  }
sig.mat<-sig.func()

pander(sig.mat,justify='left',keep.line.breaks=TRUE)
```

**Comment by cocinerox** [comment]
Try `'\\ '` instead of `' '`.

**Comment by daroczig** [comment]
Good question! But this is how `pandoc` transforms markdown to HTML/PDF/etc., so it's out of the scope of `pander`. But we also faced this issue, and found in the [`pandoc` manual](http://pandoc.org/README.html#extension-escaped_line_breaks) that trailing space and empty lines are ignored, so you either disabled that (with bunch of unexpected results) or use the workaround (hard line breaks) as @cocinerox suggested (and as we do e.g. in `pander.CrossTable`)/

**Comment by cocinerox** [comment]
Actually, if I'm right, the `'\\ '` is parsed as a [nonbreaking space](http://pandoc.org/README.html#extension-all_symbols_escapable) thus the cell will not be empty just invisible. Hard line breaks can be used within cells, e.g. `'first line\\\nsecond line'`.

**Comment by daroczig** [comment]
Oh, I did not realize that the example has empty cells -- I though it has empty lines in the same cell below the signature line, something like:

```r
> pander(matrix(c('_________________________________________________________\\\nName\\\nTitle\\\n\\\n\\\n\\\n', letters[1:3]), nrow = 2), keep.line.breaks = TRUE)

---------------------------------------------------------- -
_________________________________________________________\ b
                          Name\                              
                          Title\                             
                            \                                
                            \                                
                            \                                

                            a                              c
---------------------------------------------------------- -
```

This works fine after e.g. HTML conversion.

Sorry for the confusion, I though @cocinerox referred to this -- probably because for non-breaking space, I always use `&nbsp;`, which worked fine with all document formats so far :)

Anyway, I think I'll leave this ticket as closed, as it's outside of the scope of `pander`, but might be wrong -- please reopen at any time.
