### ISSUE TITLE
Pandoc.convert overwrites input markdown file

### ISSUE THREAD

**Issue by petrelharp** [Rapporter/pander#173]
Pandoc.convert if called on a markdown file, silently modifies the *input* file, by adding a footer. This seems to me to be bad behavior, and is not mentioned in the documentation, which says only that Pandoc.convert is used to "convert specified file [...] to other formats like HTML". 

MWE:

1. Create a file called `test.md` with some text.
2. Call `pander::Pandoc.convert(f="test.md")`.
3. Note the file has changed.

**Comment by daroczig** [comment]
Thanks for spotting this! To be honest, I never thought someone will use `Pandoc.convert` per se, it was created to be used by `Pandoc.brew`, but you are right, this is a very bad and silly behavior.

This can be resolved for now by setting `footer=FALSE` in the `Pandoc.covert` call. In the future releases, I will make this as the default settings.

**Comment by daroczig** [comment]
Another issue might be, that we force `utf-8` encoding before passing to `pandoc`, but this should not cause much trouble: https://github.com/Rapporter/pander/blob/master/R/convert.R#L74

Please reopen if that would be the case.

**Comment by petrelharp** [comment]
I agree, overwriting the original file, even to convert it to `utf-8`, is not very nice.  Why not just do it with a temp file in all cases?

Hm, don't think I can reopen this myself.

**Comment by daroczig** [comment]
Sorry for the long delay with resolving this -- above fix should avoid any updates in the original md file.
