### ISSUE TITLE
lapply in pander help

### ISSUE THREAD

**Issue by shaneData** [Rapporter/pander#179]
The R Markdown code below explains the output I am getting and the output I would like to get for an HTML file . For the example part that I would like to see as my output, I don't want to display the tables manually as I did. I would like to have pander() show tables in the correct output through lapply. I read https://github.com/Rapporter/pander/issues/16 but still have not had any luck. Any help would be greatly appreciated!

Thank you, Shane.

```
\`\`\`{r, echo=FALSE, warning=FALSE, message=FALSE, comment=NA}
library(plyr)
library(pander)
\`\`\`

\`\`\`{r pander, echo=FALSE, warning=FALSE, message=FALSE, comment=NA}

each = c("cyl","carb")

print("what output is with lapply")
pander(
  lapply(1:length(each), function(z) {
    ddply(mtcars, c(each), summarise, sum = sum(hp))
  })
)

example =   lapply(1:length(each), function(z) {
    ddply(mtcars, c(each), summarise, sum = sum(hp))
  })

print("What I want output to be")
pander(example[[1]])
pander(example[[2]])
\`\`\`
```

Edit by daroczig: tried to escape code chunk

**Comment by daroczig** [comment]
What about the following based on disabling the `knitr.auto.asis` option:
* http://blog.rapporter.net/2014/09/pander-tables-inside-of-knitr.html
* https://github.com/Rapporter/pander/issues/142#issuecomment-66619769

```r
```{r pander-no-auto-knitr, echo=FALSE, results='asis'}
panderOptions('knitr.auto.asis', FALSE)
each = c("cyl","carb")
for (z in 1:length(each)) {
    pander(ddply(mtcars, c(each), summarise, sum = sum(hp)))
}
`` ``
```

Please let me know how it works for you and reopen if you face any issues.

**Comment by shaneData** [comment]
Thanks for the quick reply, exactly what I needed!
