### ISSUE TITLE
sessionInfo() problem

### ISSUE THREAD

**Issue by dmurdoch** [Rapporter/pander#191]
This document gives an error when processed:

    ---
    title: "Untitled"
    author: "Duncan Murdoch"
    date: "June 30, 2015"
    output: pdf_document
    ---

    ```{r}
    pander::pander(sessionInfo(), compact=TRUE)

    pander::pander(sessionInfo(), compact=FALSE)
    ```
The first `sessionInfo()` is fine:

```r
pander::pander(sessionInfo(), compact=TRUE)
```

**R version 3.2.0 Patched (2015-04-28 r68272)**

**Platform:** x86_64-apple-darwin13.4.0 (64-bit) 

**locale:**
en_CA.UTF-8||en_CA.UTF-8||en_CA.UTF-8||C||en_CA.UTF-8||en_CA.UTF-8

**attached base packages:** 
_stats_, _graphics_, _grDevices_, _utils_, _datasets_, _methods_ and _base_

**loaded via a namespace (and not attached):** 
_magrittr(v.1.5)_, _tools(v.3.2.0)_, _htmltools(v.0.2.6)_, _Rcpp(v.0.11.6)_, _pander(v.0.5.3)_, _stringi(v.0.5-5)_, _rmarkdown(v.0.7)_, _knitr(v.1.10.5)_, _stringr(v.1.0.0)_, _digest(v.0.6.8)_ and _evaluate(v.0.7)_

The second `sessionInfo()` comes out with a subscript out of bounds error:
```r
pander::pander(sessionInfo(), compact=FALSE)
```

**R version 3.2.0 Patched (2015-04-28 r68272)**

**Platform:** x86_64-apple-darwin13.4.0 (64-bit) 

**locale:**
en_CA.UTF-8||en_CA.UTF-8||en_CA.UTF-8||C||en_CA.UTF-8||en_CA.UTF-8
Quitting from lines 10-13 (course.Rmd) 
Error in elements[[i]] : subscript out of bounds
Calls: <Anonymous> ... pandoc.list.return -> paste -> sapply -> lapply -> FUN

**Comment by daroczig** [comment]
Thank you very much for reporting this -- the bug was triggered by not having any "other attached packages", which triggered an error in `pandoc.list`. This should be fixed now.

Also, thank you very much for attending my tutorial today, it was a great honor to have your kind interest and company!

**Comment by dmurdoch** [comment]
On 30/06/2015 11:42 PM, Gergely Daróczi wrote:
> Thank you very much for reporting this -- the bug was triggered by not
> having any "other attached packages", which triggered an error in
> |pandoc.list|. This should be fixed now.
> 
> Also, thank you very much for attending my tutorial today, it was a
> great honor to have your kind interest and company!
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rapporter/pander/issues/191#issuecomment-117353648>.
> 

Thank you for the quick fix!  I was familiar with rmarkdown, but not
with pander:  it looks really interesting.

Duncan

**Comment by daroczig** [comment]
Thank you very much for your kind words, I'd be more than happy to try to answer any question you may have. Best, Gergely
