### ISSUE TITLE
pander table in loop

### ISSUE THREAD

**Issue by spmasterman** [Rapporter/pander#195]
pander doesn't seem to output a table when called in a loop

I have a large data frame (tradeSeries) that has a column 'drone' that is used to group the rows - I want to display a separate table for each 'section' of the tradeSeries, filtered by the unique values of drone 

library(pander)
for (droneName in drones[,1]) { 
  t <- tradeSeries[tradeSeries$drone %in% c(droneName), 3:9]
  pander(t, caption=paste("Trade Series ",droneName))       <--- This doesn't print anything
  print(t)              <-- this successfully prints the data I want, but not as a well formatted table
}  
pander(t, caption=paste("Trade Series ",droneName))      <-- this successfully prints the last table

I'm pretty new to all this R/pander stuff so I'm almost certainly making a rookie mistake :) If you want me to make a more concise/complete example of what I think isn't working, let me know...?

**Comment by daroczig** [comment]
A reproducible minimal example would be welcomed, but I suspect you have to disable the `auto.asis` option for `knitr` -- described at https://github.com/Rapporter/pander/issues/179#issuecomment-110228899

Please let me know if it works.

**Comment by spmasterman** [comment]
Genius!

Thats exactly what I needed to do.

Many thanks - you just saved me a whole Friday of frustration :)

**Comment by daroczig** [comment]
Thanks for the prompt feedback, I'm happy you found this useful.
