### ISSUE TITLE
0 row data.frame/matrix displayed as if they had a single NA row

### ISSUE THREAD

**Issue by BrianDiggs** [Rapporter/pander#205]
# Summary

A `data.frame` or `matrix` with no rows is displayed the same way as one with a single row filled with `NA`s. As theses are different things, they should be displayed differently.

# Discussion

In R, a zero row `data.frame` and `matrix` are well defined, and sometimes useful, constructs. Separately, a row in a `data.frame` or `matrix` can contain all `NA`s. This happens most frequently when selecting rows with a logical vector and on element is `NA`. Pander, however, displays these the same way. I believe pander's display is correct for a single `NA` row, but not correct for a zero-row version.

This came up in the discussion of #204.

# Example code
```r
library("pander")

explore <- function(x) {
  cat("print:\n")
  print(x)
  cat("\ndim:\n")
  print(dim(x))
  cat("\nstr:\n")
  str(x)
  cat("\npander:\n")
  pander(x)
  invisible(x)
}

explore(mtcars[1,][NA,])
explore(mtcars[FALSE,])
mtcars.mx <- as.matrix(mtcars)
explore(mtcars.mx[1,,drop=FALSE][NA,])
explore(mtcars.mx[FALSE,])
```

# Output
```r
> explore <- function(x) {
+   cat("print:\n")
+   print(x)
+   cat("\ndim:\n")
+   print(dim(x))
+   cat("\nstr:\n")
+   str(x)
+   cat("\npander:\n")
+   pander(x)
+   invisible(x)
+ }
> 
> explore(mtcars[1,][NA,])
print:
   mpg cyl disp hp drat wt qsec vs am gear carb
NA  NA  NA   NA NA   NA NA   NA NA NA   NA   NA

dim:
[1]  1 11

str:
'data.frame':   1 obs. of  11 variables:
 $ mpg : num NA
 $ cyl : num NA
 $ disp: num NA
 $ hp  : num NA
 $ drat: num NA
 $ wt  : num NA
 $ qsec: num NA
 $ vs  : num NA
 $ am  : num NA
 $ gear: num NA
 $ carb: num NA

pander:

---------------------------------------------------
 &nbsp;   mpg   cyl   disp   hp   drat   wt   qsec 
-------- ----- ----- ------ ---- ------ ---- ------
 **NA**   NA    NA     NA    NA    NA    NA    NA  
---------------------------------------------------

Table: Table continues below

 
--------------------------------
 &nbsp;   vs   am   gear   carb 
-------- ---- ---- ------ ------
 **NA**   NA   NA    NA     NA  
--------------------------------

> explore(mtcars[FALSE,])
print:
 [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
<0 rows> (or 0-length row.names)

dim:
[1]  0 11

str:
'data.frame':   0 obs. of  11 variables:
 $ mpg : num 
 $ cyl : num 
 $ disp: num 
 $ hp  : num 
 $ drat: num 
 $ wt  : num 
 $ qsec: num 
 $ vs  : num 
 $ am  : num 
 $ gear: num 
 $ carb: num 

pander:
------------------------------------------------------------------
 mpg   cyl   disp   hp   drat   wt   qsec   vs   am   gear   carb 
----- ----- ------ ---- ------ ---- ------ ---- ---- ------ ------
 NA    NA     NA    NA    NA    NA    NA    NA   NA    NA     NA  
------------------------------------------------------------------

> mtcars.mx <- as.matrix(mtcars)
> explore(mtcars.mx[1,,drop=FALSE][NA,])
print:
 mpg  cyl disp   hp drat   wt qsec   vs   am gear carb 
  NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA 

dim:
NULL

str:
 Named num [1:11] NA NA NA NA NA NA NA NA NA NA ...
 - attr(*, "names")= chr [1:11] "mpg" "cyl" "disp" "hp" ...

pander:

----------------------------------------------------
 mpg   cyl   disp   hp   drat   wt   qsec   vs   am 
----- ----- ------ ---- ------ ---- ------ ---- ----
 NA    NA     NA    NA    NA    NA    NA    NA   NA 
----------------------------------------------------

Table: Table continues below

 
-------------
 gear   carb 
------ ------
  NA     NA  
-------------

> explore(mtcars.mx[FALSE,])
print:
     mpg cyl disp hp drat wt qsec vs am gear carb

dim:
[1]  0 11

str:
 num[0 , 1:11] 
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:11] "mpg" "cyl" "disp" "hp" ...

pander:
------------------------------------------------------------------
 mpg   cyl   disp   hp   drat   wt   qsec   vs   am   gear   carb 
----- ----- ------ ---- ------ ---- ------ ---- ---- ------ ------
 NA    NA     NA    NA    NA    NA    NA    NA   NA    NA     NA  
------------------------------------------------------------------
``` 
Results generated by pander 0.5.2 except for the results of the pander call for zero row `data.frame` and `matrix` which are extrapolated from the stated behavior in #204. 

The expected result for a zero row `data.frame` or `matrix` might be

```r
------------------------------------------------------------------
 mpg   cyl   disp   hp   drat   wt   qsec   vs   am   gear   carb 
----- ----- ------ ---- ------ ---- ------ ---- ---- ------ ------
------------------------------------------------------------------
```
maybe with a notation that it is zero row, much like `print` gives ("`<0 rows> (or 0-length row.names)`"). I am not sure the exact format that it should have, but I do not think it should be indistinguishable from a single `NA` row version.

**Comment by daroczig** [comment]
Thank you very much for the thoughtful feedback.

Unfortunately, I am not sure about what should be shown for such empty table and we (@RomanTsegelskyi and I) came up with the idea of showing a row of `NA` in such case. Another solution might be not showing anything at all, as there's no data in the table -- only the header is there.

AFAIK, there is no support for a header-only table in Pandoc's markdown. When I tried to convert your above suggested table to HTML, I got an incorrect structure, where the header can hardly be identified.

So please let's discuss what's the appropriate format to show:
* keeping the current behavior with inserted `NA`
* rendering a one-row table (having the header as a standalone row -- that we might emphasize manually with stars):

        ----- ----- ------ ---- ------ ---- ------ ---- ---- ------ ------
         mpg   cyl   disp   hp   drat   wt   qsec   vs   am   gear   carb 
        ----- ----- ------ ---- ------ ---- ------ ---- ---- ------ ------

* returning nothing
* anything else?

**Comment by RomanTsegelskyi** [comment]
Here is my 2 cents - something should be definately return, because silent failure seems like a bad practice. R does print for empty objects

```r
> mtcars[mtcars$mpg < 0, ]
 [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
<0 rows> (or 0-length row.names)
```

However, I am torn between option 1 and 2, leaning a bit more towards second option, thought it still not very clear that table is empty

**Comment by daroczig** [comment]
Another alternative might be to return ~nothing instead of `NA`:

```r
> pander(mtcars[mtcars$am < 0, ], missing = '&nbsp;')

----------------------------------------------------------------------------
 mpg    cyl    disp    hp    drat    wt    qsec    vs     am    gear   carb 
------ ------ ------ ------ ------ ------ ------ ------ ------ ------ ------
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
----------------------------------------------------------------------------
```

None of these seems optimal to me :disappointed: 

Let's try to come up with some better solution -- I try to ask around what other think about this.

**Comment by BrianDiggs** [comment]
I agree that it should return something. The two precedents in R are to return just the headers (as a `matrix` does) or to return the headers and some sort of note (as a `data.frame` does)

```r
> as.matrix(mtcars)[FALSE,]
     mpg cyl disp hp drat wt qsec vs am gear carb
> mtcars[FALSE,]
 [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
<0 rows> (or 0-length row.names)
```
The matrix behavior corresponds most closely to the second option (return just the headers, but as a row). If you could make a multi-column spanning cell with the text "`<0 rows>`" or similar, that would be my vote; some brief looking around makes me think markdown does not have multi-column cells in its basic syntax, though. I don't know if there is an extension that can be relied on. Baring that, I would lean toward filling a row with `&nbsp;` (or `&#8203;`, zero-width space) because that would allow the headers to truly be headers. If Markdown allowed a table to have a header but no rows, that would be best; something that is the illusion of there not being a row would a lesser choice.

**Comment by daroczig** [comment]
Thanks for the feedback. Unfortunately col/row spanning is not supported in markdown :(

But if the "table" does not even have a header, we already throw a warning and return nothing else:

```r
> pander::pander(matrix(0, nrow = 0, ncol = 5))
Warning message:
In pandoc.table.return(...) :
  Object is empty and without header. No output will be produced
```

What about throwing a similar warning on empty tables with a header? We might first return the header in a normal table with strong emphasis and then the warning, something like:

```r
> pandoc.table(names(mtcars), emphasize.strong.rows = 1)

------- ------- -------- ------ -------- ------ -------- ------ ------ -------- --------
**mpg** **cyl** **disp** **hp** **drat** **wt** **qsec** **vs** **am** **gear** **carb**
------- ------- -------- ------ -------- ------ -------- ------ ------ -------- --------

> warning('No rows in the table')
Warning message:
No rows in the table 
````

What do you think?

**Comment by RomanTsegelskyi** [comment]
@daroczig, should we go with your last suggestion for this issue? IMHO that seems reasonable and a bit better then current solution with NAs

**Comment by daroczig** [comment]
Yeah, I have no better idea.

**Comment by RomanTsegelskyi** [comment]
Fixed in https://github.com/Rapporter/pander/commit/b4b3b2ae4b537e584a2887090cfb871180127eca
