### ISSUE TITLE
Update to CrossTable function in descr

### ISSUE THREAD

**Issue by Chris-M-P** [Rapporter/pander#211]
The author of the `descr` package has updated the `CrossTable` function to include options to remove row and column totals (see https://github.com/jalvesaq/descr/issues/2). However, `pander` reinserts the row and column totals. Would it be possible to update `pander` to take advantage of these options?

The author of `descr` suggests looking at the `CreateNewTab` function in `CrossTable.R`

**Comment by RomanTsegelskyi** [comment]
@Chris-M-P thanks for reporting this. I will try to look into it this week

**Comment by Chris-M-P** [comment]
Thanks

**Comment by RomanTsegelskyi** [comment]
@Chris-M-P, I create #213, please have a look if it's okay and we will merge it then

**Comment by Chris-M-P** [comment]
I've tested the updated package and it works fine
