### ISSUE TITLE
Missing blank line in single line multiline table

### ISSUE THREAD

**Issue by Dris101** [Rapporter/pander#224]
As per the `pandoc` docs, a single line multi-table should have a blank line before the row of dashes that ends the table, otherwise the table may be interpreted as a simple table.
(see the docs for the `multiline_tables` extension)

**Comment by daroczig** [comment]
Thanks for reporting this, much appreciated. A quick addition: this only happens if we have a one-liner `multiline` table without a header, e.g.:

```r
> pander(data.frame(a = 'lorem ipsum', b = 'foobar'), style = 'multiline', split.cells = 5)

------------
  a     b   
----- ------
lorem foobar
ipsum       
------------
```
