### ISSUE TITLE
Encoding mark and possible encoding problem with table.expand()

### ISSUE THREAD

**Issue by huashan** [Rapporter/pander#228]
Hi, I recently had a CJK encoding problem with `pandoc.table.return()`. Below is the reproducible code:

```r
a1 = data.frame(`中文` = '122', a='1中文1', b = 'a', stringsAsFactors = F)
lapply(a1, Encoding)
ss = pandoc.table.return(a1)
Encoding(ss)
```

It turns out that the table head and cell text have differenct encoding. However, they are concatenate together and R doesn't aware the differenct encoding. There are possible automatic encoding coversions with calls to `gsub()`. Using `useBytes = TRUE` for `gsub` will solve the problem. But I think it might be better if the call to `pander_tableExpand_cpp` in `table.expand()` could preserve R's character encoding. I don't know much about the mechanism between R and C function. But a simple test would prove that:

```r
a1$a = iconv(a1$a, 'gb2312', 'UTF-8')
r2 = apply(a1, 1, pander:::tableExpand_cpp, rep(10, 3), rep('', 3),
         rep(',', 3), 'simple')
Encoding(r2)  # unknown 
```

**Comment by daroczig** [comment]
Hi @huashan, running your example here returns:

![pander 228](https://cloud.githubusercontent.com/assets/495736/10095086/eaca2eca-631b-11e5-9344-6f42fcea676f.png)

I 'm not sure what's the problem with that markdown output. We already check byte-by-byte vs character-by-character comparison for the cell widths -- although I've never thought of an issue having multiple character encodings in the same table :)

Please let me know how the table should look like.

**Comment by huashan** [comment]
Hi @daroczig,

You got the results correct. What's your environment? I am using Windows 7 with Chinese locale and options(encoding = 'native.enc')

From the above code, all three columns of `a1` have encodings of 'unknown'

lapply(a1, Encoding)
# unknown unknown unknown

**Comment by daroczig** [comment]
I'm on Linux with the most recent dev version of `pander`:

```r
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Arch Linux

locale:
 [1] LC_CTYPE=hu_HU.utf8       LC_NUMERIC=C             
 [3] LC_TIME=en_US.UTF-8       LC_COLLATE=en_US.UTF-8   
 [5] LC_MONETARY=en_US.UTF-8   LC_MESSAGES=hu_HU.utf8   
 [7] LC_PAPER=hu_HU.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=hu_HU.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pander_0.5.3

loaded via a namespace (and not attached):
[1] tools_3.2.1  Rcpp_0.12.1  digest_0.6.8
```

The `Encoding` is `unkown` except for the second column:

```r
> lapply(a1, Encoding)
$中文
[1] "unknown"

$a
[1] "UTF-8"

$b
[1] "unknown"
```

I will try this on Windows as well -- but until then, can you please paste the results of `pander` as text and as a screenshot as well?

**Comment by huashan** [comment]
I've tested with `pander` version 0.5.2 and 0.5.3

![snap1](https://cloud.githubusercontent.com/assets/2095265/10095846/5bb92626-639f-11e5-89ec-9fec79ce08ab.jpg)

**Comment by daroczig** [comment]
Unfortunately, I cannot get my old Windows XP installation to work with CJK characters, so I will need some more time to be able to debug this. Until then, can you please verify if the output renders fine or it has some issues after passing to `pandoc`?

**Comment by daroczig** [comment]
I got temporary access to a Windows 7 machine, but could not reproduce this issue with the CJK characters. Can you please provide some more details with eg the locale you are using? A full `sessionInfo()` output would be helpful.

But I think if you set the `Encoding` for the column names as well, your above example will work fine. Quick demo:

```r
Encoding(ss) <- 'UTF-8'
Encoding(names(ss)) <- 'UTF-8'
pander(ss)
```

Please reopen with more details if this is still an issue.
