### ISSUE TITLE
pander conflicts with dplyr

### ISSUE THREAD

**Issue by realAkhmed** [Rapporter/pander#234]
Hello everyone,

It appears there is an issue such that attaching `dplyr` impacts `pander` options. The code below fails to produce a valid PDF (the number is supposed to be displayed as `11,255,608` and not `11255608`).

    ---
    title: "Bigmark example"
    output: pdf_document
    ---
    
    ```{r}
    library(dplyr)
    library(pander)
    
    df <- structure(list(n = 11255608L), .Names = "n", row.names = c(NA, 
    -1L), class = c("tbl_df", "tbl", "data.frame"))
    
    pander::pander(df, big.mark = ',')
    ```

However, if you just remove `library(dplyr)` from it. It will produce the expected PDF with the number displayed as `11,255,608`.

**Comment by daroczig** [comment]
Thanks for reporting this issue, which should be fixed with the above commit -- so please [install the development version](http://rapporter.github.io/pander/#installation) of `pander` and try:

```r
> library(dplyr)
> library(pander)
> df <- structure(list(n = 11255608L), .Names = "n", row.names = c(NA, -1L), class = c("tbl_df", "tbl", "data.frame"))
> pander::pander(df, big.mark = ',')

----------
    n     
----------
11,255,608
----------
```

**Comment by realAkhmed** [comment]
Wow, that was fast! Checked the Github version and it indeed works correctly now. Thanks a lot!
