### ISSUE TITLE
Update `rms` methods

### ISSUE THREAD

**Issue by daroczig** [Rapporter/pander#236]
`rms` support was added in #207, but a recent update in the package broke functionality. @RomanTsegelskyi, can you please have a look and fix it? See eg https://travis-ci.org/Rapporter/pander/builds/99020762

I think an elegant solution might be to check the version of `rms` and support old and new versions (as for `ggplot2` in https://github.com/Rapporter/pander/commit/ce75329da31e9ea6a784e2fde254815cbb591095), but I'm fine with dropping support for older builds if we can specify min version number for this suggested package.

**Comment by daroczig** [comment]
@RomanTsegelskyi, will you have some time to look into this?

**Comment by RomanTsegelskyi** [comment]
@daroczig, sorry, I was travelling during the holidays, now back in Seattle and will look into all the issues this week

**Comment by daroczig** [comment]
Sounds good, thanks for looking into this.

**Comment by RomanTsegelskyi** [comment]
After some exploration it seems to me that test failure was introduced by the regression in `rms`, for which I logged the issue (https://github.com/harrelfe/Hmisc/issues/38). The code we were using was provided as part of #207, so I changed the test example to use official exaples from rms documentation in #237, which might be more robust aganist changes in future.

**Comment by daroczig** [comment]
Thanks @RomanTsegelskyi. Travis reported the `rmarkdown` package to be missing and thus the tests failing. Are you looking into this or should I?

**Comment by RomanTsegelskyi** [comment]
It seems that new version of `knitr` is defaulting to `rmarkdown`. I added it to the list of recommended packages

**Comment by daroczig** [comment]
Thanks a lot!

**Comment by daroczig** [comment]
@RomanTsegelskyi, as per the referenced `Hmisc` ticket, it seems to me that the reported issue should not happen -- no? I mean Travis is installing the most recent version of `Hmisc` and `rms`, but in the ticket it was said that the most recent CRAN version of these packages should not fail. Now I am not sure if that's the case, so I'll leave this to you if any further follow-ups are needed or not.

**Comment by RomanTsegelskyi** [comment]
I still feel that it was connected with incorrect version of the `Hmisc`, because I can't reproduce it anymore after updaing `Hmisc`

**Comment by daroczig** [comment]
Sounds good, thanks for the feedback.
