### ISSUE TITLE
Row and column names wrapped in quotes in pandoc.ftable output

### ISSUE THREAD

**Issue by chadbdot** [Rapporter/pander#242]
On my setup, `pandoc.ftable` wraps row and column names in quotes. Our conversations in other threads indicate that this isn't normal/desired behavior. Here's an example:

```
> test.table <- xtabs(wt ~ gear + carb, aggregate(wt ~ gear + carb, mtcars, mean))

> pander(ftable(test.table))

------ ------ ----- ------- ---- ------- ---- ----
       "carb"  "1"    "2"   "3"    "4"   "6"  "8" 

"gear"                                            

 "3"          3.047  3.56   3.86 4.6858   0    0  

 "4"          2.072 2.68375  0   3.09375  0    0  

 "5"            0   1.8265   0    3.17   2.77 3.57
------ ------ ----- ------- ---- ------- ---- ----
```

My `sessionInfo` is as follows:

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pander_0.6.0

loaded via a namespace (and not attached):
[1] tools_3.2.3  Rcpp_0.12.3  digest_0.6.9

```

Happy to provide additional details if need be. Thanks!

**Comment by daroczig** [comment]
Can you please install the most recent dev version of the package from GitHub? I think you are running `0.6` from CRAN, which indeed seems to have this issue, but this was fixed in the dev version.

To verify which version you are running, instead of `sessionInfo`, use the `session_info` function from `devtools`, to install the dev version:

```r
devtools::install_github('Rapporter/pander')
```

**Comment by chadbdot** [comment]
Ok, I just installed the dev version and am no longer having this issue. Thanks!

**Comment by daroczig** [comment]
Sounds good, thank you @chadbdot. Will push an updated to CRAN at around Q2.
