### ISSUE TITLE
Pander support for summary.felm from lfe package

### ISSUE THREAD

**Issue by janthnyr** [Rapporter/pander#243]
Package is lfe.

This package is very useful for high dimensional group fixed effects (econometrics sense of fixed effect).  It would be great to have pander tables for this summary method.

**Comment by daroczig** [comment]
Can you please add a simple example for using `summary.felm` and also describe the required output? If all you need is to print the coefficients, like what we do with `lm` by default, it should be a simple addition to `pander`.

**Comment by daroczig** [comment]
@janthnyr is it something you still need? Can you please add an example use case and reopen the ticket?
