### ISSUE TITLE
issue with pander.mtable

### ISSUE THREAD

**Issue by spedygiorgio** [Rapporter/pander#244]
I fit three regression models (pc1wkPE, pc1wkVC, pc1wkNI) then generated an mtable object

oneweekModels <- mtable('PE backed' = pc1wkPE,
                        'VC backed' = pc1wkVC,
                        'Normal Ipo' = pc1wkNI,
                        summary.stats = c('R-squared','F','p','N'))

When running pander(onedayModels) I got
Error in dimnames(x$coefficients)[[3]] : subscript out of bounds

**Comment by RomanTsegelskyi** [comment]
Thanks for reporting the issue. Can you post `pc1wkPE`, `pc1wkVC`, `pc1wkN`, so we can have a reproducible case?

**Comment by melff** [comment]
Dear all,
since memisc 0.99, the structure of "mtable" objects has changed, so that `pander.mtable()` is likely to be broken. I'll try to create a patch for this issue in the next days.
Best, Martin

**Comment by spedygiorgio** [comment]
I confirm that mmelf fix closes this issues.
