### ISSUE TITLE
Change default output when in the jupyter kernel

### ISSUE THREAD

**Issue by JanSchulz** [Rapporter/pander#249]
The jupyter notebook unfortunately only understands the `rmarkdown` syntax for tables but not the `multiline` one, so it would be nice if this syntax is used when pander is running in an r kernel:

e.g. in the options.R `.onload`:

```
.onLoad <- function(libname, pkgname) {
    # The jupyter notebook does not understand the multiline default :-(
    if (getOption("jupyter.in_kernel", FALSE)){
        default_style <- 'rmarkdown'  
    } else {
        default_style <- 'multiline'
    }
    ## pander settings
    options('pander' = list(
[...]
                'table.style'              = default_style,
[...]
```

**Comment by daroczig** [comment]
Please see above commit -- let me know how it works.

**Comment by JanSchulz** [comment]
Thanks, that helps! Reading the help file, maybe this should also be done when a knitr run is detected?

**Comment by daroczig** [comment]
Not sure why should we default to the `rmarkdown` table format instead of the `multiline` inside of `knitr`. Can you please clarify that?

**Comment by JanSchulz** [comment]
I got that impression from the help text:

> I'd suggest sticking to the default `multiline` format with the most features, except when using **`rmarkdown` v1.0** or jupyter notebook, where `multiline` is not supported (for this end the default table format is `rmarkdown` when `pander` is called inside of a jupyter notebook)

Or is that specific to rmarkdown v1 vs v2? It seems that rmarkdown is nowadays the way knitr is used...

**Comment by JanSchulz** [comment]
And just to confirm it worked:

In the current master notebook:

```R
> library(pander)
> panderOptions("table.style")
"rmarkdown"
```

**Comment by daroczig** [comment]
Ah, I see, thanks for the clarification. Yes, it's related to only to the intial version of `rmarkdown`, when the RStudio guys created an R package to transform markdown to HTML, which supported only the pipe table format -- and they changed at last to relying on `pandoc` since the [2nd version of `rmarkdown`](http://blog.rstudio.org/2014/06/18/r-markdown-v2/). So anyone using `rmarkdown` nowadays should not face this issue.

**Comment by daroczig** [comment]
Thanks for the feedback, @JanSchulz!

**Comment by JanSchulz** [comment]
So it's the same problem with the notebook: it uses `marked` javascript lib to transform the markdown, not pandoc :-(

**Comment by daroczig** [comment]
I see :(

AFAIK the old `rmarkdown` implementation used the Sundown C library: https://github.com/rstudio/markdown

But I'm glad they changed to `pandoc` after all -- I've been urging that since around ~2011 :)

**Comment by JanSchulz** [comment]
Unfortunately, the notebook will probably never switch to pandoc in the browser side, so lets hope that there will one day be a javascript library which does the whole pandoc stuff :-/ But that would prbably require that the whole "table in markdown" mess is standardized first (http://talk.commonmark.org/t/tables-in-pure-markdown/81)...
