### ISSUE TITLE
Figure and table referencing

### ISSUE THREAD

**Issue by ssinari** [Rapporter/pander#258]
Is it possible to do LaTeX style figure and table referencing using pander?

**Comment by daroczig** [comment]
`pander` has no direct helper functions for this, as fig/table references are not part of [pandoc's markdown](http://pandoc.org/README.html). Although you can use any LaTeX commands in a markdown document if your output format is PDF, but honestly -- I'd rather go with eg `xtable` for more features if you are tied to PDF. Unfortunately, this feature is not supported in other document format as far as I know -- so closing this ticket, but please feel free to reopen/create a new one if I misunderstood the question.

**Comment by ssinari** [comment]
Hello Gergely,
Thanks for the quick response. Internal links in HTML are not that foreign.
Here is how it is done: example: <a href="html_tips.html#tips">Visit the
Useful Tips Section</a>. What needs to be done is the indexing part for the
fig/tables. I understand this may not be part of the formal markdown spec.
Here is some discussion on this issue and seems to have been incorporated
in pandoc markdown:
https://github.com/jgm/pandoc/issues/261#issuecomment-50236381 and more
about scholarly markdown:
http://scholarlymarkdown.com/Scholarly-Markdown-Guide.html#differences-from-pandoc-1.
I think it might be beneficial to have the scholarly markdown syntax
supported. just my two cents.
Regards,

-- 
Shripad Sinari
University of Arizona
Statistician - BIO5 Institute
1657 E. Helen St / Keating Bldg, Cube 0200D7
Ph: (520) 626-2325
Email: shripad@email.arizona.edu

**Comment by daroczig** [comment]
Hi Shripad,

this is a great idea! I was not aware that with the most recent versions of `pandoc` it's that easy to add HTML attributes to images. Based on this, I will add an optional argument to `pandoc.image` to support this feature -- although this will be a HTML-only thing it seems.

About the indexing part: I think that should be done rather in JS as part of the HTML template used in `pandoc`. We do something similar in the package-bundled JS file to build a table of content from the `h1`, `h2` etc tags at https://github.com/Rapporter/pander/blob/master/inst/includes/javascripts/custom.js#L48

Unfortunately, the next few weeks are very busy, so please do not expect a related commit in the near future, but I will get back to this thread in early May.

Best,
Gergely

**Comment by ssinari** [comment]
Thanks Gergely,
Looking forward to it when you are done.
Regards,

-- 
Shripad Sinari
University of Arizona
Statistician - BIO5 Institute
1657 E. Helen St / Keating Bldg, Cube 0200D7
Ph: (520) 626-2325
Email: shripad@email.arizona.edu

**Comment by yasirs** [comment]
Stupid question: Why can't [reference links](http://pandoc.org/README.html#reference-links) be used for cross-referencing tables and figures?

**Comment by daroczig** [comment]
@yasirs I think the problematic point here is not how to reference stuff, but how to refer to tables and figures. Or I miss something. Can you please provide a simple example?

**Comment by yasirs** [comment]
@daroczig You are right. They're too different things.

According to https://github.com/jgm/pandoc/issues/813#issuecomment-168227636 there are pandoc-extensions for 

-  [pandoc-fignos](https://github.com/tomduck/pandoc-fignos) for figures
-  [pandoc-eqnos](https://github.com/tomduck/pandoc-eqnos) for equations
-  [pandoc-tablenos](https://github.com/tomduck/pandoc-tablenos) for tables

Pander could support these in the meantime.

**Comment by daroczig** [comment]
Good resources, thank you, @yasirs!

**Comment by daroczig** [comment]
A quick question before I push some updates regarding this:

- referencing tables via `pandoc-tablenos` is already pretty easy, as you can include the label in the caption as per https://github.com/tomduck/pandoc-tablenos#basic-syntax -- do you think it's OK or should we add a new argument to `pandoc.table`?
- referencing images is a bit trickier with `pandoc-fignos` as the label should be appended right after the image path, so this needs a new argument in `pandoc.image`. Is it something you would use?

What do you think?

**Comment by ssinari** [comment]
Hello Gergely,
I would prefer a new argument that takes the identifier as a string just to
keep them separate.
Regards,
Shripad.

On Saturday, May 14, 2016, Gergely Daróczi <notifications@github.com> wrote:

> A quick question before I push some updates regarding this:
>
>    - referencing tables via pandoc-tablenos is already pretty easy, as
>    you can include the label in the caption as per
>    https://github.com/tomduck/pandoc-tablenos#basic-syntax -- do you
>    think it's OK or should we add a new argument to pandoc.table?
>    - referencing images is a bit trickier with pandoc-fignos as the label
>    should be appended right after the image path, so this needs a new argument
>    in pandoc.image. Is it something you would use?
>
> What do you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Rapporter/pander/issues/258#issuecomment-219239481>
>


-- 
Shripad
Tucson, Az.
Sent from my iPad. Please excuse typos.

**Comment by yasirs** [comment]
I think the label should be an optional argument to table with the default being the chunk name, to be compatible with bookdown and it's behavior with knitr::kable. Also, the tables produced as part of pandoc.test.

**Comment by guillaumechaumet** [comment]
Hi guys. Did this new feature is available?

**Comment by krlmlr** [comment]
I use the following in conjunction with [bookdown](https://bookdown.org/yihui/bookdown/tables.html):

```r
pander(..., caption = "(\\#tab:table-label) Table caption")
```

In the text, I then refer to the table via `\@ref(tab:table-label)` .

**Comment by guillaumechaumet** [comment]
I use this solution 
`
pander(...,caption=\\label{tabs:NSV})
`

and then `\ref{tabs:NSV}` in the text part.

Thanks

**Comment by ssinari** [comment]
great thanks for the feature.

-- 
Shripad Sinari
University of Arizona
Statistician - BIO5 Institute
1657 E. Helen St / Keating Bldg, Cube 0200D7
Ph: (520) 626-2325
Email: shripad@email.arizona.edu

**Comment by daroczig** [comment]
Thanks all for your very helpful feedback! I'm closing this in favor of the above-referenced ticket and hope to get this done there soon.
