### ISSUE TITLE
pander.htest gives errors if the test name is too long

### ISSUE THREAD

**Issue by yasirs** [Rapporter/pander#260]
This contrived code reproduces the error:

```
> a <- mtcars; a$am[a$am==0] <- "Manual transmission"; a$am[a$am==1] <- "Automatic transmission";
> pander(chisq.test(table(as.factor(a$am),as.factor(a$cyl))[c("Manual transmission", "Automatic transmission"),]))
Error in check_caption(caption) : 
  The caption should be exactly one string.
```
This is due to R returning the name of the test object as vector of two strings (perhaps to separate it into two lines). I've suggested a fix with https://github.com/Rapporter/pander/pull/261

**Comment by daroczig** [comment]
Thanks for reporting this bug, and also for the suggested fix! Much appreciated. I've added a comment in the PR, can you please fix that before I can merge?

**Comment by yasirs** [comment]
Thanks @daroczig, PR changed.

**Comment by daroczig** [comment]
Thanks a lot, PR is merged.
