### ISSUE TITLE
table should split cells in case of a list

### ISSUE THREAD

**Issue by yasirs** [Rapporter/pander#262]
Consider the code:
```
> a <- data.table(city="NY", desc=c("VeryBig", "BigApple", "Finance", "Media", "RentIsTooDamnHigh"))
> a <- a[,.(desc = list(desc)),by=city]
> pandoc.table(a, split.cells=5)

-------------------------------------------------------
 city                        desc                      
------ ------------------------------------------------
  NY   VeryBig,BigApple,Finance,Media,RentIsTooDamnHigh
-------------------------------------------------------
```
I think logically, we want to split the list in desc to be multi line on the comma. As a workaround one can do
```
a$desc <- sapply(a$desc, function(x) paste(x, collapse = ", "))
```
for each column with lists before calling pandoc.table.

**Comment by daroczig** [comment]
Good point. But let's think about this from a more general point of view: shouldn't we split on eg any character besides `[a-zA-Z]` and accented chars? Or a list of known punctuations, like dot, semi-colon etc. What do you think?

**Comment by yasirs** [comment]
Yes, absolutely I agree there should be an option to split on any desired
character. Unfortunately strwrap doesn't support this. We need a custom
function. I could only think of a sequential program to do this. Is that
the way to go?


On the other hand conceptually splitting lists can be different
from splitting on a character.

**Comment by daroczig** [comment]
One workaround here, as just came to my mind, that `pander` already supports hyphenation:

```r
> pandoc.table(a, split.cells = 5, use.hyphening = TRUE)

-----------------
 city     desc   
------ ----------
  NY     Very-   
          Big-   
          ,B-    
          igA-   
          ppl-   
          e,-    
         Finan-  
         ce,M-   
         edia-   
          ,Re-   
        ntIsToo- 
        DamnHigh 
-----------------
```

This might be a better way for the original purpose. What do you think?

**Comment by yasirs** [comment]
I think you are right. While lists inside tables are possible, I think they behave in unexpected ways and so may not be practical.

**Comment by daroczig** [comment]
Closing as adding support for lists inside of tables would potentially open up Pandora's box and lot of side effects.
