### ISSUE TITLE
pander.table can't work with tables containing numerical and list types

### ISSUE THREAD

**Issue by yasirs** [Rapporter/pander#263]
Consider:
```
> a <- data.frame(a=c(1,2), b=c(2,3), c=c("a,b","c,d"), stringsAsFactors = F)
> a$c <- strsplit(a$c, ",")
> pandoc.table(a)
Error in `colnames<-`(`*tmp*`, value = c("a", "b", "c")) : 
  length of 'dimnames' [2] not equal to array extent
Error during wrapup: argument "fun" is missing, with no default
```
However, if all the columns are characters, it works fine
```
> b <- a
> b$a <- as.character(b$a)
> b$b <- as.character(b$b)
> pandoc.table(b)

------------
 a   b   c  
--- --- ----
 1   2  a, b

 2   3  c, d
------------
```

**Comment by daroczig** [comment]
I am not 100% sure yet if it's something we should handle inside of `pander`. I mean a `data.frame` having a `list` column is highly unlikely, and if we start supporting such weird things, I have no idea what might come up next :) Let me think about this for a few days, but looking forward to any other views on this.

**Comment by daroczig** [comment]
Closing as adding support for lists inside of tables would potentially open up Pandora's box and lot of side effects -- as per #262
