### ISSUE TITLE
Possible bug in table.alignment.default: "Wrong number of parameters passed: justify"

### ISSUE THREAD

**Issue by realAkhmed** [Rapporter/pander#269]
Hello! Consider the following code
```r
library(pander)
panderOptions('table.alignment.default',
     function(df) ifelse(sapply(df, is.numeric), 'right', 'left'))

df <- structure(list(comm_id = c("xxxxx", "yyyyy"), crawl_ccrawler_id = c(2L, 
2L)), .Names = c("comm_id", "crawl_ccrawler_id"), row.names = 1:2, class = "data.frame")

pander(summary(df))
```

For some reason it produces the following error
```
Error in pandoc.table.return(...) : 
  Wrong number of parameters (12 instead of *2*) passed: justify
```

This is clearly caused by `table.alignment.default` option above (no error happens if the option is removed) but I don't see where number 12 is coming from since ` ifelse(sapply(df, is.numeric), 'right', 'left')` clearly generates 2 strings as expected?

I am using the latest version from Github

**Comment by daroczig** [comment]
I think you do not need the `summary` call there -- can you please confirm that?

Eg this works without any problem:

```r
> pander(df)

-----------------------------
comm_id     crawl_ccrawler_id
--------- -------------------
xxxxx                       2

yyyyy                       2
-----------------------------
```

But checking the `summary` indeed returns 12 (6*2) booleans:

```r
> sapply(summary(df), is.numeric)
Length:2           Class :character   Mode  :character                 <NA> 
             FALSE              FALSE              FALSE              FALSE 
              <NA>               <NA>        Min.   :2          1st Qu.:2   
             FALSE              FALSE              FALSE              FALSE 
       Median :2          Mean   :2          3rd Qu.:2          Max.   :2   
             FALSE              FALSE              FALSE              FALSE 
```

If you want to have a special function to provide the alignment for the `summary`, you will have to define a smarter helper function than the `sapply` one. Does it answer your question? Please reopen if not and/or let me know if you have any other questions.

**Comment by realAkhmed** [comment]
@daroczig hmm.... the purpose of that code was to print the summary of `df`, not the content of `df`. I don't think removing `summary` resolves this issue

Consider this:
```{r}
library(pander)
panderOptions('table.alignment.default','left')

df <- structure(list(comm_id = c("xxxxx", "yyyyy"), crawl_ccrawler_id = c(2L, 
2L)), .Names = c("comm_id", "crawl_ccrawler_id"), row.names = 1:2, class = "data.frame")

pander(summary(df))
```

This is the desired output
```
--------------------------------------
comm_id            crawl_ccrawler_id  
------------------ -------------------
Length:2           Min.  :2           

Class :character   1st Qu.:2          

Mode :character    Median :2          

NA                 Mean :2            

NA                 3rd Qu.:2          

NA                 Max.  :2           
--------------------------------------
```

**Comment by realAkhmed** [comment]
Oh, I think I see what to do: it is my code that misusing the function by ignoring the differences between tables and data.frames.

If I change `sapply(summary(df), is.numeric)` to `apply(summary(df),2, is.numeric)` then it works as desired!

```r
panderOptions('table.alignment.default',
     function(df) ifelse(apply(summary(df),2, is.numeric), 'right', 'left'))
```

Thanks a lot!

**Comment by daroczig** [comment]
Thanks for the clarification, this makes sense.
But your custom function using sapply returns 12 true/false values instead
of 2. In short, you need to come up with a smarter fn to return only 2
alignments for a summary object -- which is a bit out of the scope of the
pander pkg, but happy to help if you get stuck -- just let me know.

--
Sent from a mobile phone with an annoying input interface, pls excuse my
brevity/spelling issues.

**Comment by realAkhmed** [comment]
@daroczig Thanks a lot! Yes, it is completely my oversight: I didn't realize that the type changes from data.frame to table after `summary`. This just requires a simple one-line change to fix my code (above).

**Comment by daroczig** [comment]
I'm glad you managed to solve this, thanks for the feedback.
