### ISSUE TITLE
Is it possible to keep trailing zeros?

### ISSUE THREAD

**Issue by huashan** [Rapporter/pander#27]
I noticed that the behavior of `pander()` and `pandoc.table()` are different. I like the way `pander()` does to keep the trailing zeros. Is it possible to let `pandoc.table()` do the same thing?

panderOptions("digits", 4)
a<-c(7, 7.1, 7.233)

> pander(a)
> _7_, _7.100_ and _7.233_
> 
> pandoc.table(a)
> 7 7.1 7.233

**Comment by perlmonger** [comment]
Has this behavior changed?  I am on Windows, r R x64 3.2.4 Revised

The first part of the example stays the same:
```{r}
> panderOptions('keep.trailing.zeros', F)
>  p(a)
[1] "_7_, _7.1_ and _7.233_"
> panderOptions('keep.trailing.zeros', T)
>  p(a)
[1] "_7.000_, _7.100_ and _7.233_"
> 
```
But, this does not turn out like in the example above:

```{r}
> a<-c(7, 7.1, 7.233)
> panderOptions('keep.trailing.zeros', T)
> pandoc.table(a)
- --- -----
7 7.1 7.233
- --- -----

```
Also, it doesn't work for the mtcars example either.

```{r}
> panderOptions('keep.trailing.zeros', T)
> pander(mtcars[1:3, 1:5])

--------------------------------------------------
      &nbsp;         mpg   cyl   disp   hp   drat 
------------------- ----- ----- ------ ---- ------
   **Mazda RX4**     21     6    160   110   3.9  

 **Mazda RX4 Wag**   21     6    160   110   3.9  

  **Datsun 710**    22.8    4    108    93   3.85 
--------------------------------------------------
```

**Comment by daroczig** [comment]
This is a regression bug, thanks for the report. Can you please file a new ticket with the exact same content as you above comment? I could fo that to, but this way you would get notified about the fix (I will have some time to debug this early next week).

**Comment by perlmonger** [comment]
Ok, will do.  And thanks for all your work on this.   It really makes my life easier.  I particularly like the emphasize.strong.cells and the like.  Some day you should add  color options as well.  Red would pop even better than bold.  :)
