### ISSUE TITLE
pandoc.formula with caption causes error

### ISSUE THREAD

**Issue by puterleat** [Rapporter/pander#274]
For example: 

```
f <- y~x
pandoc.formula(f, caption="Blah")
```

Generates this error:

> Error in !is.null(caption) && caption != "" && check_caption(caption) : 
>   invalid 'y' type in 'x && y'

**Comment by daroczig** [comment]
Thanks for reporting this. Please test if above commit resolve the issue.

**Comment by puterleat** [comment]
Works for me. Thanks for fixing so quickly.
