### ISSUE TITLE
Tables fail to render inside of fullwidth environment with tufte classes

### ISSUE THREAD

**Issue by elbamos** [Rapporter/pander#275]
I'm not sure if this is more of a pander issue or a knitr issue.  So I'm going to post in both places.  

The tufte classes (handout, book, etc.) have a `fullwidth` environment.  If a pander table is created in that environment, the LaTeX typesetting engine fails to parse the table.

**Comment by daroczig** [comment]
Can you please post a minimal example for this, eg an Rmd file?

**Comment by elbamos** [comment]
I can try to put one together; I ultimately resolved the issue by using kable with the booktabs package, so I haven't looked at this in a few weeks.

**Comment by daroczig** [comment]
I guess this is due to placing markdown inside of a LaTeX env, which will not be transformed to LaTeX by `pandoc` as per http://pandoc.org/MANUAL.html#raw-tex:

> Inline TeX commands will be preserved and passed unchanged to the LaTeX and ConTeXt writers.
