### ISSUE TITLE
pander.cph fails with rms version 5.0-0

### ISSUE THREAD

**Issue by kent37** [Rapporter/pander#283]
In version 5.0-0 of the `rms` package, `rms::reVector` was renamed to `rms::reListclean`. This breaks `pander.cph` which uses `rms::reVector`. For example, using `f` as defined in `help(cph)`:

    > pander(f)
    Error: 'reVector' is not an exported object from 'namespace:rms'

**Comment by daroczig** [comment]
Thanks for this report! I'm planning to remove these methods from the `pander` package and submitting pull requests to the related R package repos, so that the maintainers can update these if things change. Planning to do that in a few weeks, currently busy with some other projects.
