### ISSUE TITLE
captioning in bookdown::tufte_book2

### ISSUE THREAD

**Issue by tormodb** [Rapporter/pander#291]
Thanks for this great package! 

I realize that this is a pretty particular request. I am writing reports using bookdown::tufte_book2 format. When using ```knitr::kable``` for producing tables, the caption is put in a marginnote/sidenote according to the tufte style. However, kable tables are very limited, and I have been relying on ```pander::pandoc.table``` to split long cells and all the other table options that pander provides. I am even able to use bookdown cross-referencing by inserting "(\\#tab:label)" as a prefix for the caption.
The last piece of the puzzle missing is that pandoc.table puts the caption in the main column of the document, and not in the marginnote. Is this possible to achieve? Can I use the caption function of knitr::kable in pandoc.table?

**Comment by daroczig** [comment]
As far as I know, the caption format in markdown is pretty standard, so not sure what might be the difference between `kable` and `pander` there, but happy to look into it. Can you please provide a minimal example on the problem eg including a `kable` and `pander` table in the `bookdown::tufte_book2` format?

**Comment by tormodb** [comment]
Thanks for the prompt reply. The following two attachments reproduce the issue (the .rmd.txt file must be changed to .rmd in order to run, but .rmd files were not supported as attachment.)

[reprex.Rmd.txt](https://github.com/Rapporter/pander/files/803657/reprex.Rmd.txt)
[reprex.pdf](https://github.com/Rapporter/pander/files/803658/reprex.pdf)

**Comment by daroczig** [comment]
I'm on mobile so cannot test right now, but the stylesheets used in the two
tables seems to be different as well, which suggests it might be due to the
different default markdown format used. That'd be a bit strange though, but
can you pls test pander with style = "rmarkdown"?

--
Sent from a mobile phone with an annoying input interface, pls excuse my
brevity/spelling issues.

**Comment by daroczig** [comment]
I'm closing this in favor of the above-referenced ticket and hope to get this done there soon.
