### ISSUE TITLE
No extra line for table.continues

### ISSUE THREAD

**Issue by gurol** [Rapporter/pander#292]
Is it possible to put no extra line at all for table continues (default: "Table continues below")? If I set an empty string (i.e. `panderOptions('table.continues', '')`)  there is still an empty line among table parts.

**Comment by daroczig** [comment]
```r
> panderOptions('table.continues', '')
> pander(head(mtcars))

-----------------------------------------------------------------------------
        &nbsp;           mpg    cyl   disp   hp    drat    wt     qsec    vs 
----------------------- ------ ----- ------ ----- ------ ------- ------- ----
     **Mazda RX4**        21     6    160    110   3.9    2.62    16.46   0  

   **Mazda RX4 Wag**      21     6    160    110   3.9    2.875   17.02   0  

    **Datsun 710**       22.8    4    108    93    3.85   2.32    18.61   1  

  **Hornet 4 Drive**     21.4    6    258    110   3.08   3.215   19.44   1  

 **Hornet Sportabout**   18.7    8    360    175   3.15   3.44    17.02   0  

      **Valiant**        18.1    6    225    105   2.76   3.46    20.22   1  
-----------------------------------------------------------------------------

 
------------------------------------------
        &nbsp;           am   gear   carb 
----------------------- ---- ------ ------
     **Mazda RX4**       1     4      4   

   **Mazda RX4 Wag**     1     4      4   

    **Datsun 710**       1     4      1   

  **Hornet 4 Drive**     0     3      1   

 **Hornet Sportabout**   0     3      2   

      **Valiant**        0     3      1   
------------------------------------------
```

So there are two empty lines between the tables. Do you want to reduce that to one empty line? In markdown, the number of empty doesn't really matter as far as I know.

**Comment by gurol** [comment]
The screenshot below was taken from a Knitr generated HTML file and shows my request. I actually want to display a single record (row) with lots of columns in stacked lines with no vertical space.

<img width="702" alt="pandercontinuedtableverticalspace" src="https://cloud.githubusercontent.com/assets/14318443/23783156/684f8330-056a-11e7-9845-630191e888c2.png">

Thank you.

**Comment by daroczig** [comment]
@gurol I'm closing this, as I think that's rather a CSS and not a markdown-related question -- you have three separate HTML tables, where you could decrease the horizontal padding/margin between those via CSS. You cannot control that by markdown. Does it make sense?
