### ISSUE TITLE
Option to prevent row names from appearing in a pander table

### ISSUE THREAD

**Issue by stevenranney** [Rapporter/pander#301]
[This answer on StackOverflow](https://stackoverflow.com/questions/21018646/how-do-i-remove-row-names-when-using-pander-to-brew-a-report) suggests that Pander removes row names automatically when the row names start with `1`. When row names don't start with `1`, there's no way to remove the row names if the data are in a dataframe:

    data.frame(a = sample(LETTERS, 10), 
                      b = sample(LETTERS, 10)) %>%
    tail(5) %>% 
    pander()

produces

    ----------------
     &nbsp;   a   b 
    -------- --- ---
     **6**    Y   B 

     **7**    F   O 

     **8**    B   H 

     **9**    R   Y 

     **10**   W   X 
    ----------------

Can Pander be updated to include a method for preventing the inclusion of row names in a table?

I'm using Pander v0.6.0 with R 3.3.0 on Windows 7.

**Comment by daroczig** [comment]
Thanks for opening this ticket and reminding me on about #282 -- please try the dev version installed from GH.
