### ISSUE TITLE
panderOptions and xtabs

### ISSUE THREAD

**Issue by hr70** [Rapporter/pander#303]
Hi,
using package pander version 0.6.0, there seems to be an issue with panderOptions and objects of class 'xtabs'.

example:
library(pander)
panderOptions('decimal.mark', ',')
panderOptions('big.mark', '.')
dat <- data.frame(x = 1000*(1:4), y = c("A","A","B","B"), z = c("C","D","C","D"))
tab <- xtabs(x ~ y + z, data = dat)
pander(tab) # not ok - big.mark in effect only for the first column (C)
pander(unclass(tab)) # ok for all columns

Regards
Henrik

**Comment by daroczig** [comment]
Hey, thanks for reporting this. Can you please check the dev version installed from GH? Seems to work fine here:

```r
> pander(tab) # not ok - big.mark in effect only for the first column (C)

------------------------
 &nbsp;     C       D   
-------- ------- -------
 **A**    1.000   2.000 

 **B**    3.000   4.000 
------------------------

> pander(unclass(tab)) # ok for all columns

------------------------
 &nbsp;     C       D   
-------- ------- -------
 **A**    1.000   2.000 

 **B**    3.000   4.000 
------------------------
```

Please reopen if the dev version is still affected
