### ISSUE TITLE
Perhaps a typo in readme?

### ISSUE THREAD

**Issue by rrodrigueznt** [Rapporter/pander#316]
Hi! New to document rendering I've reach this great tool! Please, just in order of clarify, do both tags described in the Brew to Pandoc section look the same as they read now of should the first of them be written as `<% ... %>`?
 
![brewtopandoc 20171227132255](https://user-images.githubusercontent.com/1550835/34381581-b19c6406-eb09-11e7-8c67-71fa14c49876.png)

Thanks!

**Comment by daroczig** [comment]
Thanks :+1:
