### ISSUE TITLE
Too much indentation in nested list

### ISSUE THREAD

**Issue by rubenarslan** [Rapporter/pander#323]
The following R code, when rendered via rmarkdown

````r
```{r}
pander::pander(list(w = (list(x = list(y=list(z="bla"))))))
```
````

yields

  * **w**:

      * **x**:

              * **y**:

                          * **z**: bla

i.e. the last two sub-levels are shown as code. 

I thought this could somehow could be fixed, by reducing the multiplier for indent.level in `pandoc.indent` and `pandoc.list.return` from 4 to 2, but there is someplace else where extra spaces are being introduced that I haven't figured out yet.

**Comment by daroczig** [comment]
Oh, great catch, thanks! I've just pushed a potential fix for this, can you please check?

**Comment by rubenarslan** [comment]
confirmed fixed!
