### ISSUE TITLE
Coming archiving on CRAN?

### ISSUE THREAD

**Issue by elinw** [Rapporter/pander#324]
Hi,

We got this notice today:

> This concerns the CRAN packages
> 
>   CONS DCM IAPWS95 MplusAutomation PCADSC QVM RSDA brr carpenter
>   cleanEHR codebook dataMaid desctable docxtools eclust funModeling
>   mscstexta4r mscsweblm4r packagefinder pander pubh rapport rapportools
>   rmda skimr summarytools userfriendlyscience veccompare
> 
> maintained by one of you:
> <list of 23 packages>
> 
> We have repeatedly asked for an update fixing the check problems
> shown on
>   <https://cran.r-project.org/web/checks/check_results_pander.html>
> with no reply from the maintainer thus far.
> 
> Thus, package pander is now scheduled for archival on 2018-07-19, and
> archiving this will necessitate also archiving its strong reverse
> dependencies.
> 
> Please negotiate the necessary actions.
> 
> Best

Can you tell us what is going on and if you intend to fix?  Do you need help?
For my package (skimr) we'd hate to lose pander support.

**Comment by daroczig** [comment]
Sorry for the trouble, I do have plans to fix this, but have been busy/traveling in the past months. To keep it short, I will fix this before the deadline.

**Comment by MaximeWack** [comment]
Hi, thank you for your answer!

A quick fix would be to remove the offending example, however all it does is hide the error.

A correct fix would be to change `if (author != '') {` to `if (any(author != '')) {` and `if(title != '') {` to `if (any(title != '')) {`

I'd also recommend sanitizing those character vector to remove empty strings prior to concatenation with `paste0`.

**Comment by daroczig** [comment]
The failing example has been fixed and a new version will be soon pushed to CRAN.

**Comment by daroczig** [comment]
v0.6.2 has been submitted to CRAN, thanks all

**Comment by ekstroem** [comment]
Wonderful, thanks!
