### ISSUE TITLE
Single spaced output option

### ISSUE THREAD

**Issue by trinker** [Rapporter/pander#327]
**pander** returns its output as a double spaced table.  When it gets converted to whatever format (e.g., html) this doesn't matter but the plain text is also of interest.  Having the ability to remove the double spacing can be useful.  COuld this be a feature for options?

I asked this as a Stackoverflow question and want to link the two posts: https://stackoverflow.com/a/53045049/1000343

**Comment by daroczig** [comment]
You mean not having an extra line-break between the lines? That's part of the `multiline` specs of `pandoc.` Maybe try with `style = 'simple'`?

```r
> pander(mtcars[1:5, 1:5], style = 'simple')


        &nbsp;           mpg    cyl   disp   hp    drat 
----------------------- ------ ----- ------ ----- ------
     **Mazda RX4**        21     6    160    110   3.9  
   **Mazda RX4 Wag**      21     6    160    110   3.9  
    **Datsun 710**       22.8    4    108    93    3.85 
  **Hornet 4 Drive**     21.4    6    258    110   3.08 
 **Hornet Sportabout**   18.7    8    360    175   3.15 
```

**Comment by trinker** [comment]
thanks...that was what I was after
