### ISSUE TITLE
Error if list element is of class 'Date' (bug?) 

### ISSUE THREAD

**Issue by tdeenes** [Rapporter/pander#328]
Maybe I am missing something obvious, but this code results in an error (version 0.6.2):

```
pander(list(x = as.Date("2018-11-05")))
```

The problem is caused by `pander:::pander.Date` which passes all dots arguments to `pander:::pandoc.date` which passes the args further to `pander:::pandoc.date.return` which does not have `...` in its arguments. Note that `pander.list` contains this line:
```
res.i <- paste(capture.output(pander(x[[i]], indent = indent + 1)), collapse = "\n")
```
, and because of the above, the argument `indent` is passed to `pander:::pandoc.date.return`, which of course fails to process it.

**Comment by daroczig** [comment]
Oh, good catch, and thanks for the detailed report.
