### ISSUE TITLE
Pander doesn't display international characters for me.

### ISSUE THREAD

**Issue by ymer** [Rapporter/pander#340]
Example of R studio session:

http://www.jsmp.dk/pander/pander_test.utf8.md.html

**Comment by daroczig** [comment]
Can you pls try with the dev version installed from GH? Seems to be a duplicate of #296

**Comment by ymer** [comment]
Indeed that fixes it! I thought I had the newest dev, but it turned out I didn't. Apologies for any inconvenience, and thanks for fixing #296.

**Comment by daroczig** [comment]
Awesome, thanks for the feedback
