### ISSUE TITLE
pander::pander(style="simple", ...) does not play well with MS Word output

### ISSUE THREAD

**Issue by slyrus** [Rapporter/pander#342]
It's a bit of a challenge to make a short reproducible as this relies on outputting an Rmarkdown file to word (docx) format, but if I use style="simple", then the table does not render properly in word. Leaving that out (yielding style="multiline", I think) allows things to work.

**Comment by daroczig** [comment]
Sorry, this is not really a `pander` question: this R package transforms the R object into Pandoc's markdown, which then can transform the markdown to other document formats, eg MS Word. Maybe try getting help on this by posting a minimal example on the issue (eg what `pander` returns with the `simple` style) at https://github.com/jgm/pandoc
