### ISSUE TITLE
Striped tables?

### ISSUE THREAD

**Issue by slyrus** [Rapporter/pander#343]
I find myself needing to use pander::pander instead of knitr::kable(format="latex", ...). And I really miss my striped tables. Is there any way to get this effect (still using latex) but using pander::pander? Alternatively, I could try to convert my rmarkdown text (with things like ~ for subscript) into latex before calling kintr::kable, but I don't now how to do that either. Thanks!

**Comment by daroczig** [comment]
`pander` generates markdown that knows not much about table formatting -- that's something you can do with custom HTML or LaTeX markup or general stylesheets. Eg you can make all your tables striped with a CSS stylesheet or LaTeX setting/macro.

BTW if you want to fine-tune your tables, I don't think markdown (or `pander`) is the right tool, but go straight for LaTeX or HTML or MS Word, eg via `xtable` etc
