### ISSUE TITLE
Release on CRAN

### ISSUE THREAD

**Issue by billdenney** [Rapporter/pander#347]
As discussed in #280, a new CRAN release would help.  This issue will assist with the discussion around creating that new release.

@daroczig, to answer the question from the other issue, yes.  I'll try to start some specific issue identification and make PRs (or help identify where changes are needed) to get there.

**Comment by billdenney** [comment]
I rapidly hit an error (I can't readily fix C++ issues):

```
c:/Rtools/mingw_64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o pander.dll tmp.def RcppExports.o helpers.o pandoc.o -LC:/PROGRA~1/R/R-36~1.3/bin/x64 -lR
   RcppExports.o:RcppExports.cpp:(.rdata+0x838): undefined reference to `pander_splitLine_cpp'
   RcppExports.o:RcppExports.cpp:(.rdata+0x850): undefined reference to `pander_tableExpand_cpp'
   collect2.exe: error: ld returned 1 exit status
   no DLL was created
   ERROR: compilation failed for package 'pander'
```

I got that when trying to run `devtools::load_all()` after cloning the repository.  It appears to relate to how `Rcpp::compileAttributes()` works.

**Comment by daroczig** [comment]
Thanks a lot @billdenney :bow: 

Unfortunately, this clearly shows that Windows has been always a bit neglected in this repo ... eg myself being a Linux user and (so thus) unit tests are only running on Linux as well -- but we should fix that latter.

Please let me know if you have time to look into adding appveyor support for Windows CI, otherwise I will take a look and also figure out the above issue.

Thanks again!

**Comment by billdenney** [comment]
@daroczig, I don't think that this is a Windows issue.  The problem occurs with something about how Rcpp is rewriting source files.  (Now, maybe that is Windows-specific in which case I'll take back my first sentence.)

**Comment by daroczig** [comment]
I've set up AppVeyor to be able to test this on Windows, and although there are quite some issues -- but the Rcpp build went fine: https://ci.appveyor.com/project/daroczig/pander

Meanwhile, Travis is misbehaving ... so cannot run the automated tests on Linux :sweat_smile: 

I will try to get back to this soon, but no promises at the moment.

**Comment by daroczig** [comment]
was released on 2022-03-18

**Comment by billdenney** [comment]
Thanks!
