### ISSUE TITLE
Quality-of-life request: Invisibly return table in pander.data.frame and pandoc.table

### ISSUE THREAD

**Issue by dhicks** [Rapporter/pander#353]
`pander.data.frame()` returns NULL, and from its documentation it's not obvious that this is intended and that the call needs to be replaced with `pandoc.table.return()` to return the table.  I spent a very confusing half-hour this morning trying to figure out why a bit of debugging code appeared to generate the table but didn't write anything to disk.

**Comment by daroczig** [comment]
I'm sorry that this is confusing, but the original design of the package and the generic `pander` S3 approach was designed this way. From its documentation:

![image](https://user-images.githubusercontent.com/495736/158902378-c53e0320-3e37-4e5a-a5f6-afebf2f6e4af.png)

I hope this helps -- closing the issue, but please reopen if you have any further concerns or create a PR to update/fix docs.
