### ISSUE TITLE
want table with image and line.break at the same time

### ISSUE THREAD

**Issue by datiums** [Rapporter/pander#358]
I was generating a table with Rmarkdown driven by pander.

It support image inside table which is pretty good.

Now I want to have text in one cell to be splitted with line breaks.

I have tried to add `panderOptions('keep.line.breaks', TRUE)` but seems not work.

Can someone let me know if it support and how please?

**Comment by daroczig** [comment]
Try using hard line breaks (e.g. `\\`) inside `grid` tables. Search for "hard line break" at https://pandoc.org/MANUAL.html

**Comment by datiums** [comment]
> Try using hard line breaks (e.g. `\\`) inside `grid` tables. Search for "hard line break" at https://pandoc.org/MANUAL.html

It works~
